create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  result_id text not null,
  product text not null check (product in ('tips', 'pdf')),
  paypal_order_id text not null unique,
  status text not null default 'created',
  created_at timestamptz not null default now()
);

create table if not exists public.results (
  result_id text primary key,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.unlocks (
  id bigint generated by default as identity primary key,
  result_id text not null,
  product text not null check (product in ('tips', 'pdf')),
  paypal_order_id text not null unique,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  unique (result_id, product)
);

alter table public.orders enable row level security;
alter table public.unlocks enable row level security;
alter table public.results enable row level security;

create unique index if not exists unlocks_result_product_idx on public.unlocks (result_id, product);
