-- ============================================================
-- 펫과나(Pet&Na) Supabase 스키마 v2
-- ============================================================

-- 1. pets 테이블
CREATE TABLE IF NOT EXISTS public.pets (
    id BIGINT PRIMARY KEY,
    user_id UUID NOT NULL DEFAULT auth.uid(),
    name TEXT NOT NULL,
    breed TEXT,
    type TEXT,
    "imageUrl" TEXT,
    age TEXT,                       -- 표시용 문자열 ("2살 (청소년기)")
    weight NUMERIC(6,2),            -- 숫자형으로 변경 (kg)
    gender TEXT,
    personality TEXT,
    hunger INTEGER DEFAULT 70,
    happy INTEGER DEFAULT 80,
    "roomName" TEXT,
    "iqScore" INTEGER,
    "iqTitle" TEXT,
    "iqDesc" TEXT,
    "sajuData" JSONB,
    "harmonyData" JSONB,
    "mbtiCode" TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. posts 테이블 (comments는 별도 테이블로 분리 — 하단 참고)
CREATE TABLE IF NOT EXISTS public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL DEFAULT auth.uid(),
    pet_name TEXT NOT NULL,
    pet_avatar TEXT,
    content TEXT,
    image TEXT,
    is_video BOOLEAN DEFAULT false,
    video_url TEXT,
    likes INTEGER DEFAULT 0,
    comments JSONB DEFAULT '[]'::jsonb,
    attached_walk JSONB,               -- 산책 데이터 (walk.js)
    attached_ai_health JSONB,          -- AI 건강 분석 결과 (ai-health.js)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. profiles 테이블
CREATE TABLE IF NOT EXISTS public.profiles (
    user_id UUID PRIMARY KEY DEFAULT auth.uid(),
    email TEXT UNIQUE NOT NULL,
    nickname TEXT,
    avatar TEXT,
    photo_url TEXT,
    theme TEXT,
    unit TEXT,
    notifications_enabled BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. albums 테이블
CREATE TABLE IF NOT EXISTS public.albums (
    id BIGINT PRIMARY KEY,
    user_id UUID NOT NULL DEFAULT auth.uid(),
    email TEXT NOT NULL,             -- 친구 공유 조회용 (profiles.email 참조)
    data JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. routes 테이블
CREATE TABLE IF NOT EXISTS public.routes (
    id BIGINT PRIMARY KEY,
    user_id UUID NOT NULL DEFAULT auth.uid(),
    email TEXT NOT NULL,
    name TEXT NOT NULL,
    coords JSONB NOT NULL,
    distance NUMERIC(8,3) NOT NULL,  -- 숫자형으로 변경 (km)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================
-- RLS 활성화
-- ============================================================
ALTER TABLE public.pets     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.albums   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.routes   ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- RLS 정책
-- ============================================================

-- pets
CREATE POLICY "pets_select_own"  ON public.pets FOR SELECT  USING (auth.uid() = user_id);
CREATE POLICY "pets_insert_own"  ON public.pets FOR INSERT  WITH CHECK (auth.uid() = user_id);
CREATE POLICY "pets_update_own"  ON public.pets FOR UPDATE  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "pets_delete_own"  ON public.pets FOR DELETE  USING (auth.uid() = user_id);

-- posts 업데이트: attached_walk, attached_ai_health 커럼 추가
-- ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS attached_walk      JSONB;
-- ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS attached_ai_health JSONB;

-- posts (소셜 피드: 조회 전체 공개, 수정·삭제는 본인만)
CREATE POLICY "posts_select_all" ON public.posts FOR SELECT  USING (true);
CREATE POLICY "posts_insert_own" ON public.posts FOR INSERT  WITH CHECK (auth.uid() = user_id);
CREATE POLICY "posts_update_own" ON public.posts FOR UPDATE  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "posts_delete_own" ON public.posts FOR DELETE  USING (auth.uid() = user_id);

-- profiles
CREATE POLICY "profiles_select_own" ON public.profiles FOR SELECT  USING (auth.uid() = user_id);
CREATE POLICY "profiles_insert_own" ON public.profiles FOR INSERT  WITH CHECK (auth.uid() = user_id);
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "profiles_delete_own" ON public.profiles FOR DELETE  USING (auth.uid() = user_id);

-- albums (본인 + 친구 공유 조회)
CREATE POLICY "albums_select_own"    ON public.albums FOR SELECT  USING (auth.uid() = user_id);
CREATE POLICY "albums_select_shared" ON public.albums FOR SELECT  USING (true);
CREATE POLICY "albums_insert_own"    ON public.albums FOR INSERT  WITH CHECK (auth.uid() = user_id);
CREATE POLICY "albums_update_own"    ON public.albums FOR UPDATE  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "albums_delete_own"    ON public.albums FOR DELETE  USING (auth.uid() = user_id);

-- routes
CREATE POLICY "routes_select_own" ON public.routes FOR SELECT  USING (auth.uid() = user_id);
CREATE POLICY "routes_insert_own" ON public.routes FOR INSERT  WITH CHECK (auth.uid() = user_id);
CREATE POLICY "routes_update_own" ON public.routes FOR UPDATE  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "routes_delete_own" ON public.routes FOR DELETE  USING (auth.uid() = user_id);

-- ============================================================
-- 성능 인덱스
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_pets_user_id    ON public.pets    (user_id);
CREATE INDEX IF NOT EXISTS idx_posts_user_id   ON public.posts   (user_id);
CREATE INDEX IF NOT EXISTS idx_posts_created   ON public.posts   (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_albums_email    ON public.albums  (email);
CREATE INDEX IF NOT EXISTS idx_routes_email    ON public.routes  (email);

-- ============================================================
-- 마이그레이션 (기존 테이블 보유 시 SQL Editor에서 실행)
-- ============================================================

-- pets 신규 컬럼 추가
-- ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS "sajuData"    JSONB;
-- ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS "harmonyData" JSONB;
-- ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS "mbtiCode"    TEXT;

-- weight 타입 변경 (기존 TEXT 데이터 있을 경우)
-- ALTER TABLE public.pets ALTER COLUMN weight TYPE NUMERIC(6,2) USING NULLIF(weight,'')::NUMERIC;

-- distance 타입 변경
-- ALTER TABLE public.routes ALTER COLUMN distance TYPE NUMERIC(8,3) USING NULLIF(distance,'')::NUMERIC;

-- 인덱스 추가 (테이블이 이미 존재하는 경우)
-- CREATE INDEX IF NOT EXISTS idx_pets_user_id  ON public.pets  (user_id);
-- CREATE INDEX IF NOT EXISTS idx_posts_user_id ON public.posts (user_id);
-- CREATE INDEX IF NOT EXISTS idx_posts_created ON public.posts (created_at DESC);
-- CREATE INDEX IF NOT EXISTS idx_albums_email  ON public.albums (email);
-- CREATE INDEX IF NOT EXISTS idx_routes_email  ON public.routes (email);

-- ============================================================
-- (선택) comments 별도 테이블 분리 — 댓글 대용량화 대비
-- ============================================================
-- CREATE TABLE IF NOT EXISTS public.comments (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     post_id BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
--     user_id UUID NOT NULL DEFAULT auth.uid(),
--     author TEXT NOT NULL,
--     text TEXT NOT NULL,
--     created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
-- );
-- ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "comments_select_all" ON public.comments FOR SELECT USING (true);
-- CREATE POLICY "comments_insert_own" ON public.comments FOR INSERT WITH CHECK (auth.uid() = user_id);
-- CREATE POLICY "comments_delete_own" ON public.comments FOR DELETE USING (auth.uid() = user_id);
-- CREATE INDEX IF NOT EXISTS idx_comments_post_id ON public.comments (post_id);
